# Numpy 学习 2019-05-08

## 创建 ndarray 的方法：

### ① Python 列表 list / tuple 创建  （使用 array() 函数）

In [2]:
import numpy as np
array = np.array([1, 2, 3, 4, 5])
array

array([1, 2, 3, 4, 5])

In [4]:
import numpy as np
array = np.array([[2, 3, 4], [7, 8, 9], [3, 4, 5]])
array

array([[2, 3, 4],
       [7, 8, 9],
       [3, 4, 5]])

In [1]:
import numpy as np
array = np.array((1, 2, 3, 4, 5, 6))
array

array([1, 2, 3, 4, 5, 6])

In [2]:
import numpy as np
array = np.array(((1, 2, 3), (4, 5, 6), (7, 8, 9)))
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### ② zeros() 元素为 0 的数组，ones() 元素为 1 的数组，empty() 元素为 随机数 的数组

In [5]:
import numpy as np
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
import numpy as np
b = np.ones((4, 5))
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
import numpy as np
c = np.empty((5, 4))
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### ③ arange() 函数创建数据序列，返回数组， (start, end, step); 

In [8]:
import numpy as np
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
import numpy as np
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

### ④ linspace() 返回数组， 元素为float (start, end, the number of elements)

In [1]:
import numpy as np
np.linspace(0, 2, 10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

## 数组基本操作：（2019-5-9）

### 算术运算符--对元素执行运算，创建一个新数组

In [7]:
import numpy as np
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [8]:
import numpy as np
a = np.array([20, 30, 40, 50])
b = np.arange(4)
c = a - b
c

array([20, 29, 38, 47])

In [12]:
import numpy as np
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b ** 2

array([0, 1, 4, 9], dtype=int32)

In [13]:
import numpy as np
a = np.array([20, 30, 40, 50])
b = np.arange(4)
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [14]:
import numpy as np
a = np.array([20, 30, 40, 50])
a < 35

array([ True,  True, False, False])

特别地，乘法运算符 * 的运算是执行元素运算

In [16]:
import numpy as np
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
             [3, 4]])
A * B

array([[2, 0],
       [0, 4]])

数组执行矩阵乘积使用 dot() 函数或方法

In [41]:
import numpy as np
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
             [3, 4]])
A.dot(B)  # A.dot() 方法

array([[5, 4],
       [3, 4]])

In [42]:
import numpy as np
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
             [3, 4]])
np.dot(A, B) # 函数

array([[5, 4],
       [3, 4]])

np.dot(A, B) 与 np.dot(B, A) 结果不一样：

In [19]:
import numpy as np
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
             [3, 4]])
np.dot(B, A)

array([[2, 2],
       [3, 7]])

一维数组矩阵乘积：内积

In [22]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a, b) # 1*4 + 2*5 + 3*6

32

### 修改现有数组-- 如 +=， *= 运算

In [29]:
import numpy as np
a = np.ones((2, 3), dtype=int)
b = np.random.random((2, 3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [30]:
import numpy as np
a = np.ones((2, 3), dtype=int)
b = np.random.random((2, 3))
a *= 3
b += a
b

array([[3.83440792, 3.40282538, 3.22472632],
       [3.07170639, 3.01671308, 3.32014513]])

In [34]:
import numpy as np
a = np.ones((2, 3), dtype=int)
b = np.random.random((2, 3))
a *= 3
a += b

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

### 不同类型的数组执行运算，数组运算结果的类型对应于更一般或更精确的数组（称为向上转换的行为）。计算机对于数字的精确应该是 float 型（我的理解）

In [36]:
import numpy as np
from numpy import pi
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, pi, 3)
b.dtype.name

'float64'

In [37]:
import numpy as np
from numpy import pi
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, pi, 3)
c = a + b
c

array([1.        , 2.57079633, 4.14159265])

In [38]:
import numpy as np
from numpy import pi
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, pi, 3)
c = a + b
c
c.dtype.name

'float64'

In [39]:
import numpy as np
from numpy import pi
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, pi, 3)
c = a + b
d = np.exp(c * 1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [40]:
import numpy as np
from numpy import pi
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, pi, 3)
c = a + b
d = np.exp(c * 1j)
d.dtype.name

'complex128'

### 许多一元运算都是作为 ndarray类的方法实现，如计算数组中所有元素的总和

In [43]:
import numpy as np
a = np.random.random((2, 3))
a

array([[0.41034874, 0.53392036, 0.0684651 ],
       [0.99410037, 0.66246228, 0.24451618]])

In [50]:
import numpy as np
a = np.random.random((2, 3))
a
a.sum()

2.0231662571418427

In [51]:
import numpy as np
a = np.random.random((2, 3))
a
a.min()

0.02433528312478528

In [52]:
import numpy as np
a = np.random.random((2, 3))
a
a.max()

0.8422947219610964

### 指定 axis 参数，可以沿数组的指定轴应用操作：

In [53]:
import numpy as np
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
import numpy as np
b = np.arange(12).reshape(3, 4)
b.sum(axis=0) # 0 表示沿列计算，1 表示沿行计算

array([12, 15, 18, 21])

In [56]:
import numpy as np
b = np.arange(12).reshape(3, 4)
b.sum(axis=1) # 0 表示沿列计算，1 表示沿行计算

array([ 6, 22, 38])

In [57]:
import numpy as np
b = np.arange(12).reshape(3, 4)
b.min(axis=1)

array([0, 4, 8])

In [58]:
import numpy as np
b = np.arange(12).reshape(3, 4)
b.cumsum(axis=1) # 0, 0+1, 0+1+2, 0+1+2+3.其他行类似

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

## 通用函数：NumPy提供了常见的数学函数，如sin，cos和exp。这些函数在数组上按元素级别操作，产生一个数组作为输出

In [59]:
import numpy as np
B = np.arange(3)
B

array([0, 1, 2])

In [60]:
import numpy as np
B = np.arange(3)
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [61]:
import numpy as np
B = np.arange(3)
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [62]:
import numpy as np
B = np.arange(3)
C = np.array([2., -1., 4.])
np.add(B, C)

array([2., 0., 6.])

## 索引、切片、迭代

### 一维数组可以被索引、切片、迭代，与Python序列操作一样

In [63]:
import numpy as np
a = np.arange(10) ** 3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [64]:
import numpy as np
a = np.arange(10) ** 3
a[2]

8

In [65]:
import numpy as np
a = np.arange(10) ** 3
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [69]:
import numpy as np
a = np.arange(10) ** 3
a[:6:2] = -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [70]:
import numpy as np
a = np.arange(10) ** 3
a[: :-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0], dtype=int32)

In [73]:
import numpy as np
a = np.arange(10) ** 3
for i in a:
    print(i**(1/3.0))

0.0
1.0
2.0
3.0
3.9999999999999996
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


### 多维（Multidimensional） 数组每个轴可以有一个索引。 这些索引在元组中以逗号分隔给出：

In [74]:
import numpy as np
def f(x, y):
    return 10*x + y
b = np.fromfunction(f, (5, 4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [75]:
import numpy as np
def f(x, y):
    return 10*x + y
b = np.fromfunction(f, (5, 4), dtype=int)
b[2, 3]

23

In [76]:
import numpy as np
def f(x, y):
    return 10*x + y
b = np.fromfunction(f, (5, 4), dtype=int)
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [77]:
import numpy as np
def f(x, y):
    return 10*x + y
b = np.fromfunction(f, (5, 4), dtype=int)
b[ : , 1]

array([ 1, 11, 21, 31, 41])

In [78]:
import numpy as np
def f(x, y):
    return 10*x + y
b = np.fromfunction(f, (5, 4), dtype=int)
b[1:3, : ]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

当提供比轴数更少的索引时，缺失的索引被认为是一个完整切片：
b[i] 方括号中的表达式 i 被视为后面紧跟着 : 的多个实例，用于表示剩余轴。NumPy也允许你使用三个点写为 b[i,...]
我觉得，没必要补充三个点 ...

In [79]:
import numpy as np
def f(x, y):
    return 10*x + y
b = np.fromfunction(f, (5, 4), dtype=int)
b[-1]

array([40, 41, 42, 43])

In [81]:
import numpy as np
c = np.array([[[0, 1, 2],
              [10, 12, 13]],
             [[100, 101, 102],
             [110, 112, 113]]])
c.shape

(2, 2, 3)

In [82]:
import numpy as np
c = np.array([[[0, 1, 2],
              [10, 12, 13]],
             [[100, 101, 102],
             [110, 112, 113]]])
c[1, ...]

array([[100, 101, 102],
       [110, 112, 113]])

In [83]:
import numpy as np
c = np.array([[[0, 1, 2],
              [10, 12, 13]],
             [[100, 101, 102],
             [110, 112, 113]]])
c[..., 2]

array([[  2,  13],
       [102, 113]])

### 迭代（Iterating） 多维数组是相对于第一个轴完成的。要对数组中的每个元素执行操作，可以使用 flat 属性，该属性是数组中所有元素的迭代器

In [84]:
import numpy as np
def f(x, y):
    return 10*x + y
b = np.fromfunction(f, (5, 4), dtype=int)
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [85]:
import numpy as np
def f(x, y):
    return 10*x + y
b = np.fromfunction(f, (5, 4), dtype=int)
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


## Less 基础

### 广播（Broadcasting）规则

Broadcasting允许通用函数以有意义的方式处理具有不完全相同形状的输入。

Broadcasting的第一个规则是，如果所有输入数组不具有相同数量的维度，则“1”将被重复地添加到较小数组的形状，直到所有数组具有相同数量的维度。

Broadcasting的第二个规则是，确保沿着特定维度具有大小为1的数组表现得好像它们具有沿着该维度具有最大形状的数组的大小。假定数组元素的值沿“Broadcasting”数组的该维度相同。

在应用广播规则之后，所有阵列的大小必须匹配。

### 花式索引 & 索引技巧：使用整数数组和布尔数组进行索引

#### 索引数组索引

In [87]:
import numpy as np
a = np.arange(12) ** 2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [89]:
import numpy as np
a = np.arange(12) ** 2
i = np.array([1, 1, 3, 8, 5])
a[i] # i 数组元素作为索引值

array([ 1,  1,  9, 64, 25], dtype=int32)

In [90]:
import numpy as np
a = np.arange(12) ** 2
j = np.array([[3,4], [9, 7]])
a[j]

array([[ 9, 16],
       [81, 49]], dtype=int32)

当被索引的数组 a 是一个多维数组，单个索引数组指的是 a 的第一个维度

In [1]:
import numpy as np
palette = np.array([[0, 0, 0],
                   [255, 0, 0],
                   [0, 255, 0],
                   [0, 0, 255],
                   [255, 255, 255]])
image = np.array([[0, 1, 2, 0],
                 [0, 3, 4, 0]])
palette[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [2]:
import numpy as np
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
import numpy as np
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
import numpy as np
a = np.arange(12).reshape(3, 4)
i = np.array([[0, 1],
             [1, 2]])
j = np.array([[2, 1],
             [3, 3]])
a[i, j] # (i=0,j=2) = 2,（i=1,j=1）= 5...

array([[ 2,  5],
       [ 7, 11]])

In [6]:
import numpy as np
a = np.arange(12).reshape(3, 4)
i = np.array([[0, 1],
             [1, 2]])
j = np.array([[2, 1],
             [3, 3]])
a[i, 2]

array([[ 2,  6],
       [ 6, 10]])

In [10]:
import numpy as np
a = np.arange(12).reshape(3, 4)
i = np.array([[0, 1],
             [1, 2]])
j = np.array([[2, 1],
             [3, 3]])
a[: , j] # 不明白，需要查一下资料

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])